modLoader="javafml"
loaderVersion="[47,)"
license="Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL="https://github.com/The-Aether-Team/Treasure-Reforging/issues"

[[mods]]
modId="aether_treasure_reforging"
version="${file.jarVersion}"
displayName="Treasure Reforging"
updateJSONURL="https://github.com/The-Aether-Team/Treasure-Reforging/raw/1.20.1-develop/update.json"
displayURL="https://modrinth.com/mod/aether-treasure-reforging"
logoFile="treasure_reforging_icon.png"
credits="The Aether Team"
authors="bconlon, Oz Payn"
description='''Allows dungeon treasure equipment to be smelted down into raw materials, which can be smithed back into other treasure equipment using new templates.'''

[[dependencies.aether_treasure_reforging]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aether_treasure_reforging]]
    modId = "aether"
    mandatory = true
    versionRange = "[1.20.1-1.0.0-beta.1-forge,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_treasure_reforging]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
