modLoader="javafml"
loaderVersion="[1,)"
license="Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL="https://github.com/The-Aether-Team/Treasure-Reforging/issues"

[[mods]]
modId="aether_treasure_reforging"
version="${file.jarVersion}"
displayName="Treasure Reforging"
updateJSONURL="https://github.com/The-Aether-Team/Treasure-Reforging/raw/1.20.4-develop/update.json"
displayURL="https://modrinth.com/mod/aether-treasure-reforging"
logoFile="treasure_reforging_icon.png"
credits="The Aether Team"
authors="bconlon, Oz Payn"
description='''
    Allows dungeon treasure equipment to be smelted down into raw materials, which can be smithed back into other treasure equipment using new templates.
'''

[[dependencies.aether_treasure_reforging]]
    modId="neoforge"
    type = "required"
    versionRange="[20.4.167,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aether_treasure_reforging]]
    modId = "aether"
    type = "required"
    versionRange = "[1.20.4-1.4.1-neoforge,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_treasure_reforging]]
    modId="minecraft"
    type = "required"
    versionRange="[1.20.4,1.20.5)"
    ordering="NONE"
    side="BOTH"
